// pbrt L-system deterministic grammar parser
#ifndef PBRT_LSYSTEM_H
#define PBRT_LSYSTEM_H

#include <pbrt/paramdict.h>
#include <pbrt/pbrt.h>
#include <pbrt/util/vecmath.h>

#include <cstddef>
#include <optional>
#include <string>
#include <unordered_map>
#include <vector>

namespace pbrt {

// A single piece of branch skeleton generated by the turtle interpreter.
//
// This is intentionally independent of Curve/Cylinder.  A later geometry
// builder can choose how each segment should be represented in pbrt.
struct BranchSegment {
    Point3f start;
    Point3f end;

    Float radiusStart = 0.05f;
    Float radiusEnd = 0.05f;

    // 0 is the main axis.  Entering '[' increases the active depth by one.
    int depth = 0;

    // Index of the segment from which this segment grows, or -1 for a root.
    int parentSegmentIndex = -1;

    // Position of the F command in the expanded L-system sequence.
    std::size_t sourceSymbolIndex = 0;

    std::string ToString() const;
};

// Complete local state of the 3D turtle.
//
// The frame is right-handed and satisfies
//     up = Cross(heading, left)
// Initial frame:
//     heading = +Y, left = -X, up = +Z
struct TurtleState {
    Point3f position = Point3f(0, 0, 0);

    Vector3f heading = Vector3f(0, 1, 0);
    Vector3f left = Vector3f(-1, 0, 0);
    Vector3f up = Vector3f(0, 0, 1);

    Float branchLength = 1.f;
    Float branchRadius = 0.05f;

    int depth = 0;
    int parentSegmentIndex = -1;

    std::string ToString() const;
};

struct TurtleResult {
    std::vector<BranchSegment> branches;
    TurtleState finalState;
    std::size_t maxStackDepth = 0;

    std::string ToString() const;
};

struct LSystemDefinition {
    // Grammar
    std::string axiom;
    std::unordered_map<char, std::string> productions;

    // Parameters read from the .pbrt file
    int iterations = 0;
    Float angleDegrees = 25.f;
    Float stepLength = 1.f;
    Float radius = 0.05f;
    std::size_t maxSymbols = 1'000'000;

    // Parse parameters from Shape "lsystem".
    static std::optional<LSystemDefinition> Create(
        const ParameterDictionary &parameters, const FileLoc *loc);

    // Deterministically and simultaneously expand all symbols.
    std::optional<std::string> Expand(const FileLoc *loc) const;

    std::string ToString() const;
};

class TurtleInterpreter {
  public:
    // Supported commands:
    //
    // F  Draw a BranchSegment and move forward.
    // f  Move forward without drawing.
    // +  Yaw left around the turtle's local up axis.
    // -  Yaw right around the turtle's local up axis.
    // &  Pitch down around the turtle's local left axis.
    // ^  Pitch up around the turtle's local left axis.
    // \  Roll left around the turtle's local heading axis.
    // /  Roll right around the turtle's local heading axis.
    // |  Turn around by 180 degrees.
    // [  Push the state, then enter one deeper branch level.
    // ]  Restore the most recently pushed state.
    //
    // Other symbols (for example X or A) are ignored by the interpreter and
    // may be used as non-drawing grammar variables.
    static std::optional<TurtleResult> Interpret(
        const std::string &expanded,
        const LSystemDefinition &definition,
        const FileLoc *loc);
};

}  // namespace pbrt

#endif  // PBRT_LSYSTEM_H
